/* global $, index */
$(document).ready(function () {
  $('button').click(function () {
    loadZitat()
  })
  loadZitat()
})
function loadZitat () {
  var zufallsZitat = zitate[Math.floor(Math.random() * zitate.length)].zitat
  var zufallsAutor = zitate[Math.floor(Math.random() * zitate.length)].autor
  var zufallsWerk = zitate[Math.floor(Math.random() * zitate.length)].werk
  $('blockquote p').text(zufallsZitat)
  $('blockquote footer span').text(zufallsAutor)
  $('blockquote footer cite').text(zufallsWerk)
  
}

var zitate = [
    { zitat: 'Offen gesagt, meine Liebe: Das ist mir völlig egal.', autor: 'Clark Gable', werk: 'Vom Winde verweht'},
    { zitat: 'Ich werde ihm ein Angebot machen, das er nicht ablehnen kann.', autor: 'Marlon Brando', werk: 'Der Pate'},
    { zitat: 'Du verstehst das nicht! Ich hätte was werden können, zumindest ein klasse Boxer. Und was bin ich geworden? Ein gemeiner Lump.', autor: 'Marlon Brando', werk: 'Die Faust im Nacken'},
    { zitat: 'Toto, ich habe das Gefühl, wir befinden uns nicht mehr', werk: 'Kansas.', autor: 'Judy Garland', werk: 'Der Zauberer von Oz'},
    { zitat: 'Ich schau dir', werk: 'die Augen, Kleines', autor: 'Humphrey Bogart', werk: 'Casablanca'},
    { zitat: 'Komm schon, versüß mir den Tag', autor: 'Clint Eastwood', werk: 'Dirty Harry kommt zurück'},
    { zitat: 'Ich bin fertig für die Nahaufnahme, Mr. DeMille!', autor: 'Gloria Swanson', werk: 'Boulevard der Dämmerung'},
    { zitat: 'Möge die Macht mit dir sein!', autor: 'Alec Guinness', werk: 'Krieg der Sterne'},
    { zitat: 'Bitte anschnallen, meine Herrschaften! Ich glaube, es wird eine stürmische Nacht!', autor: 'Bette Davis', werk: 'Alles über Eva'},
    { zitat: 'Redest du mit mir?', autor: 'Robert De Niro', werk: 'Taxi Driver'},
    { zitat: 'Was wir hier haben, ist mangelnde Kommunikation.', autor: 'Strother Martin', werk: 'Der Unbeugsame'},
    { zitat: 'Ich liebe den Geruch von Napalm am Morgen.', autor: 'Robert Duvall', werk: 'Apocalypse Now'},
    { zitat: 'Liebe bedeutet, niemals um Verzeihung bitten zu müssen.', autor: 'Ali MacGraw', werk: 'Love Story'},
    { zitat: 'Das ist der Stoff aus dem die Träume sind!', autor: 'Humphrey Bogart', werk: 'Die Spur des Falken'},
    { zitat: 'E.T. nach Hause telefonieren.', autor: 'Pat Welsh', werk: 'E.T. – Der Außerirdische'},
    { zitat: 'Die nennen mich ‚Mr.‘ Tibbs!', autor: 'Sidney Poitier', werk: 'In der Hitze der Nacht'},
    { zitat: 'Rosebud.', autor: 'Orson Welles', werk: 'Citizen Kane'},
    { zitat: 'Ich hab\'s geschafft, Ma! Jetzt bin ich ganz oben!', autor: 'James Cagney', werk: 'Sprung', werk: 'den Tod'},
    { zitat: 'Ich bin fuchsteufelswild und lass mir das nicht mehr länger gefallen.', autor: 'Peter Finch', werk: 'Network'},
    { zitat: 'Louis, ich glaube, dies ist der Beginn einer wunderbaren Freundschaft.', autor: 'Humphrey Bogart', werk: 'Casablanca'},
    { zitat: 'Einer dieser Meinungsforscher wollte mich testen, ich genoss seine Leber mit ein paar Fava-Bohnen und einem ausgezeichneten Chianti.', autor: 'Anthony Hopkins', werk: 'Das Schweigen der Lämmer'},
    { zitat: 'Bond. James Bond.“ – Sean Connery', werk: 'James Bond jagt Dr. No'},
    { zitat: 'Am schönsten ist es zu Hause.', autor: 'Judy Garland', werk: 'Das zauberhafte Land'},
    { zitat: 'Ich bin groß, die Filme sind es, die heute keine Größe mehr haben.', autor: 'Gloria Swanson', werk: 'Boulevard der Dämmerung'},
    { zitat: 'Führ mich zum Schotter!', autor: 'Cuba Gooding jr.', werk: 'Jerry Maguire – Spiel des Lebens'},
    { zitat: 'Wenn ich gehe, hast du Pause!', autor: 'Dustin Hoffman', werk: 'Asphalt-Cowboy'},
    { zitat: 'Spiel es, Sam. Spiel ‚As Time Goes By‘.', autor: 'Ingrid Bergman', werk: 'Casablanca'},
    { zitat: 'Sie können die Wahrheit doch gar nicht ertragen!', autor: 'Jack Nicholson', werk: 'Eine Frage der Ehre'},
    { zitat: 'Ich will allein sein!', autor: 'Greta Garbo', werk: 'Menschen im Hotel'},
    { zitat: 'Morgen ist auch noch ein Tag!', autor: 'Vivien Leigh', werk: 'Vom Winde verweht'},
    { zitat: 'Verhaften Sie die üblichen Verdächtigen!', autor: 'Claude Rains', werk: 'Casablanca'},
    { zitat: 'Ich will genau das, was sie hatte.', autor: 'Estelle Reiner', werk: 'Harry und Sally'},
    { zitat: 'Sie werden ein größeres Boot brauchen.', autor: 'Roy Scheider', werk: 'Der weiße Hai'},
    { zitat: 'Ich komme wieder.', autor: 'Arnold Schwarzenegger', werk: 'Terminator'},
    { zitat: 'Today, I consider myself the luckiest man on the face of the earth“ – Gary Cooper', werk: 'Der große Wurf'},
    { zitat: 'Wenn du es baust, wird er kommen.', autor: 'Ray Liotta (Stimme aus dem Off)', werk: 'Feld der Träume'},
    { zitat: 'Mama hat immer gesagt, das Leben ist wie eine Schachtel Pralinen. Man weiß nie, was man kriegt.', autor: 'Tom Hanks', werk: 'Forrest Gump'},
    { zitat: 'Wir überfallen Banken.', autor: 'Warren Beatty', werk: 'Bonnie und Clyde'},
    { zitat: 'Plastik.', autor: 'Walter Brooke', werk: 'Die Reifeprüfung'},
    { zitat: 'Uns bleibt immer noch Paris.', autor: 'Humphrey Bogart', werk: 'Casablanca'},
    { zitat: 'Ich sehe tote Menschen.', autor: 'Haley Joel Osment', werk: 'The Sixth Sense'},
    { zitat: 'Niemand ist vollkommen.', autor: 'Joe E. Brown', werk: 'Manche mögen’s heiß'},
    { zitat: 'Es lebt!', autor: 'Colin Clive', werk: 'Frankenstein'},
    { zitat: 'Houston, wir haben ein Problem!', autor: 'Tom Hanks', werk: 'Apollo 13'},
    { zitat: 'Nun fragst Du Dich, ob heute Dein Glückstag ist. Ist heute dein Glückstag, Bruder?', autor: 'Clint Eastwood', werk: 'Dirty Harry'},
    { zitat: 'Du hattest mich schon beim ‚Hallo‘.', autor: 'Renée Zellweger', werk: 'Jerry Maguire – Spiel des Lebens'},
    { zitat: 'Ich habe mal einen Elefant', werk: 'meinem Schlafanzug erschossen. Wie er', werk: 'den Schlafanzug reingekommen ist, wird mir immer ein Rätsel bleiben.', autor: 'Groucho Marx', werk: 'Animal Crackers'},
    { zitat: 'Beim Baseball wird nicht geweint!', autor: 'Tom Hanks', werk: 'Eine Klasse für sich'},
    { zitat: 'Tanderadei', autor: 'Diane Keaton', werk: 'Der Stadtneurotiker'},
    { zitat: 'Der beste Freund eines Mannes ist seine Mutter.', autor: 'Anthony Perkins', werk: 'Psycho'},
    { zitat: 'Gier, leider gibt es dafür keinen besseren Ausdruck, ist gut!', autor: 'Michael Douglas', werk: 'Wall Street'},
    { zitat: 'Halte deine Freunde nahe bei dir, aber deine Feinde noch näher.', autor: 'Al Pacino', werk: 'Der Pate – Teil II'},
    { zitat: 'Bei Gott, ich werde nie mehr hungern!', autor: 'Vivien Leigh', werk: 'Vom Winde verweht'},
    { zitat: 'Da hast du mich ja wieder', werk: 'ein schönes Schlamassel hineingezogen!', autor: 'Oliver Hardy', werk: 'Die Wüstensöhne'},
    { zitat: 'Sagt Hallo zu meiner kleinen Freundin!', autor: 'Al Pacino', werk: 'Scarface'},
    { zitat: 'What a dump.“ – Bette Davis', werk: 'Der Stachel des Bösen'},
    { zitat: 'Mrs. Robinson, Sie versuchen, mich zu verführen. Oder nicht?', autor: 'Dustin Hoffman', werk: 'Die Reifeprüfung'},
    { zitat: 'Meine Herren, sie können hier nicht kämpfen, das ist der Kriegsraum.', autor: 'Peter Sellers', werk: 'Dr. Seltsam oder: Wie ich lernte, die Bombe zu lieben'},
    { zitat: 'Elementar, mein lieber Watson.', autor: 'Basil Rathbone', werk: 'Die Abenteuer des Sherlock Holmes'},
    { zitat: 'Könnt ihr nicht eure dreckigen Pfoten von meinem Körper nehmen, ihr blöden Affen!', autor: 'Charlton Heston', werk: 'Planet der Affen'},
    { zitat: 'Von allen Kaschemmen der ganzen Welt kommt sie ausgerechnet in meine', autor: 'Humphrey Bogart', werk: 'Casablanca'},
    { zitat: 'Hier ist Jacky!', autor: 'Jack Nicholson', werk: 'Shining'},
    { zitat: 'Sie sind hier!', autor: 'Heather O’Rourke', werk: 'Poltergeist'},
    { zitat: 'Sind sie außer Gefahr?', autor: 'Laurence Olivier', werk: 'Der Marathon-Mann'},
    { zitat: 'Einen Moment, einen Moment. Sie haben doch noch gar nichts gehört!', autor: 'Al Jolson', werk: 'Der Jazzsänger'},
    { zitat: 'Keine Drahtbügel, niemals!', autor: 'Faye Dunaway', werk: 'Meine liebe Rabenmutter'},
    { zitat: 'Heilige Mutter Maria, ist das das Ende von Rico?', autor: 'Edward G. Robinson', werk: 'Der kleine Caesar'},
    { zitat: 'Vergiss es, Jake. Wir sind', werk: 'Chinatown.', autor: 'Joe Mantell', werk: 'Chinatown'},
    { zitat: 'Ich war immer auf die Güte von Fremden angewiesen', autor: 'Vivien Leigh', werk: 'Endstation Sehnsucht'},
    { zitat: 'Hasta la vista, baby.', autor:'Arnold Schwarzenegger', werk: 'Terminator 2 – Tag der Abrechnung'},
    { zitat: 'Soylent Green ist Menschenfleisch!', autor: 'Charlton Heston', werk: 'Soylent Green'},
    { zitat: 'Öffne die Schleusen, HAL!', autor: 'Keir Dullea', werk: '2001: Odyssee im Weltraum'},
    { zitat: 'Striker: Das meinen Sie doch nicht ernst! Rumack: Doch, das mein ich, und nennen Sie mich nicht Ernst.', autor: 'Robert Hays und Leslie Nielsen', werk: 'Die unglaubliche Reise in einem verrückten Flugzeug'},
    { zitat: 'Hören Sie die Kinder der Nacht? Was für Musik sie machen!', autor: 'Bela Lugosi', werk: 'Dracula'},
    { zitat: 'Mein Schatz.', autor: 'Andy Serkis', werk: 'Der Herr Der Ringe: Die zwei Türme'},
    { zitat: 'Einen Martini. Geschüttelt. Nicht gerührt.', autor: 'Sean Connery', werk: 'Goldfinger'},
    { zitat: 'Ich spür die Gier, die Gier nach Tempo', werk: 'mir!', autor: 'Tom Cruise und Anthony Edwards', werk: 'Top Gun'},
    { zitat: 'Carpe diem! Nutzet den Tag, Jungs! Macht etwas Außergewöhnliches aus Eurem Leben!', autor: 'Robin Williams', werk: 'Der Club der toten Dichter'},
    { zitat: 'Mein Baby gehört zu mir!', autor: 'Patrick Swayze', werk: 'Dirty Dancing'},
    { zitat: 'Ich krieg dich schon noch. Und deinen kleinen Hund auch!', autor: 'Margaret Hamilton', werk: 'Das zauberhafte Land'},
    { zitat: 'Ich bin der König der Welt!', autor: 'Leonardo DiCaprio', werk: 'Titanic'},
    { zitat: 'Er kämpft für so viel mehr als für sich selbst. ', autor: 'Tahereh Mafi ', werk: 'Ich fürchte mich nicht'},
    { zitat: 'Schütze deine Träume, dann schützt du dein Herz. ', autor: 'Julia Adrian ', werk: 'Die Dreizehnte Fee'},
    { zitat: 'Das ist der Unterschied zwischen Regierungen und Menschen. Regierungen kümmern sich nicht, Menschen schon. ', autor: 'Mark Twain ', werk: 'A Tramp Abroad'},
    { zitat: 'Alle großen Leute waren einmal Kinder, aber nur wenige erinnern sich daran. ', autor: 'Antoine de Saint-Exupéry ', werk: 'Der kleine Prinz'},
    { zitat: 'Schmerz verlangt gespürt zu werden. ', autor: 'John Green ', werk: 'Das Schicksal ist ein mieser Verräter'},
    { zitat: 'Alles Gescheite ist schon gedacht worden, man muß nur versuchen, es noch einmal zu denken. ', autor: 'Johann Wolfgang von Goethe', werk: 'Ein Buch'},
    { zitat: 'Wenn wir die Chance in der Gegenwart nicht ergreifen, werden wir in Zukunft auf unsere Vergangenheit zurückblicken und bedauern, nichts daran geändert zu haben. ', autor: 'Jojo Moyes ', werk: 'Eine Handvoll Worte'},
    { zitat: 'Aber glaubt mir, dass man Glück und Zuversicht selbst in Zeiten der Dunkelheit zu finden vermag. Man darf nur nicht vergessen ein Licht leuchten zu lassen. ', autor: 'J.K. Rowling ', werk: 'Harry Potter und der Gefangene von Askaban'},
    { zitat: 'Wie schön ist es doch, dass niemand nicht einmal eine Sekunde lang warten muss, bevor er anfängt, die Welt zu verbessern! ', autor: 'Anne Frank ', werk: 'Anne Franks Tagebuch'},
    { zitat: 'Ein Mensch kann einsam sein, auch wenn er von vielen geliebt wird, wenn er nicht für Einen der ‘Liebste’ ist. ', autor: 'Anne Frank ', werk: 'Anne Franks Tagebuch'},
    { zitat: 'Nicht alles, was Gold ist, funkelt. Nicht jeder, der wandert, ist verloren.', autor:'J. R. R. Tolkien ', werk: 'Der Herr der Ringe'},
    { zitat: 'Wir können nichts dafür, wie wir auf die Welt gekommen sind. Wir können nichts für das, was wir sind, wir können nur entscheiden, welches Leben wir führen wollen.', autor: 'Leigh Bardugo ', werk: 'Wonder Woman'},
    { zitat: 'Ich habe schon Thunfisch-Sandwichs gegessen, die einen höheren IQ hatten als dieser Junge. ', autor: 'Kerstin Gier ', werk: 'Silber'},
    { zitat: 'Ich wette, du bist so hohl wie eine Christbaumkugel! ', autor: 'Kerstin Gier', werk:'Edelsteintriologie'},
    { zitat: 'Der Tag an dem ich starb, hat nicht wirklich Spaß gemacht.', autor:'David Safier ', werk: 'Mieses Karma'},
    { zitat: 'Hätte Jim lesen können, dann hätte er vielleicht jetzt schon einen merkwürdigen Umstand bemerkt. Aber Jim konnte eben nicht lesen. ', autor: 'Michael Ende ', werk: 'Jim Knopf'},
    { zitat: 'Ein Jammer, dass die Liebe nicht so einfach ist, wie wir uns das manchmal wünschen. Das Herz ist ein geheimnisvolles Ding, nicht wahr?  Mag es auch noch so erfüllt sein von der Liebe zu einem Menschen, findet sich darin doch immer noch ein Platz für einen anderen. ', autor: 'Erin Lindsey ', werk: 'Die Garde des Königs'},
    { zitat: 'Während er las, verliebte ich mich in ihn, so wie man in den Schlaf gleitet: langsam zuerst und dann rettungslos. ', autor: 'John Green ', werk: 'Das Schicksal ist ein mieser Verräter'},
    { zitat: 'Die Lieb’ hält Maß, die Lust hat nie genug; Die Lieb’ ist Wahrheit ganz, die Lust ganz Lug. ', autor:'William Shakespeare', werk:''},
    { zitat: 'Liebe und Verlangen sind zwei unterschiedliche Dinge: nicht alles, was man liebt, verlangt man auch; und nicht alles, wonach man verlangt, liebt man auch. ', autor: 'Miguel de Cervantes ', werk: 'Don Quijote'},
    { zitat: 'Er küsste ihre Finger so sacht, als hätten seine Lippen noch nie etwas Schöneres berührt. ', autor: 'Cornelia Funke', werk:'Reckless'},
    { zitat: 'Trotz dir, trotz mir und trotz, dass die Welt unterzugehen beginnt, liebe ich dich. ', autor: 'Margareth Mitchell ', werk: 'Vom Winde verweht'},
    { zitat: 'Und wenn er mich fragt: ‘Du liebst mich. Wahr oder nicht wahr?!’ Dann antworte ich: ‘Wahr’. ', autor: 'Suzanne Collins', werk: 'Die Tribute von Panem'},
    { zitat: 'Liebe ist eben genauso ungerecht verteilt auf dieser Welt wie Regen. Die einen kriegen entschieden zu viel davon ab und die anderen zu wenig. ',autor:'Cornelia Funke', werk: 'Die Wilden Hühner und die Liebe'},
    { zitat: 'Liebe lässt dich die heimlichen Plätze in einer anderen Person finden, selbst jene, von denen wir nicht wussten, dass es sie gibt, selbst jene, die sie selbst nicht dachten wundervoll zu nennen.« von <em>Diana Peterfreund ', werk: 'For Darkness Shows the Stars'},
    { zitat: 'Freundschaft ist sicherlich der beste Balsam für die Wunden einer enttäuschten Liebe. ', autor: 'Jane Austen'},
    { zitat: 'Ich möchte, dass jeder dich trifft. Du bist meine Lieblingsperson aller Zeiten. ', autor: 'Jay Asher ', werk: 'Tote Mädchen lügen nicht'},
    { zitat: 'Wenn Wolken die Sonne verbergen, gibt es immer irgendwo einen Silberstreifen, der mich ermahnt, nicht aufzugeben. ', autor: 'Matthew Quick ', werk: 'Silver Linings'},
    { zitat: 'So viele Sterne der Himmel, so viele Mädchen hat dein Rom. ', autor: 'Ovid ', werk: 'Ars amatoria'},
    { zitat: 'Wer nicht an Magie glaubt, wird sie niemals entdecken. ', autor: 'Roald Dahl', werk: 'something'},
    { zitat: 'Man sieht nur mit dem Herzen gut. Das Wesentliche ist für die Augen unsichtbar. ', autor: 'Antoine de Saint-Exupéry ', werk: 'Der kleine Prinz'},
    { zitat: 'Der Schnee sah im Mondlicht seltsam aus, wie Puderzucker auf einer Stadt aus Papier. ', autor: 'Cornelia Funke ', werk: 'Der Herr der Diebe'},
    { zitat: 'Es war ein schöner Ausklang für den schönsten Tag meines Lebens. ', autor: 'John Green ', werk: 'Eine wie Alaska'},
    { zitat: 'Der Mensch betrachtet vieles aus der Ferne, um sich seiner Angst nicht stellen zu müssen, als dass er versucht, seine Wünsche aus der Nähe zu erreichen. ', autor: 'Dan Brown ', werk: 'Sakrileg'},
    { zitat: 'Es sagt viel über die Welt aus, mein Kind, sagte der Vater zum Knaben, dass die Dummen glücklich sind und die Schlauen Depressionen haben. ', autor: 'Marc Uwe Kling ', werk: 'Die Känguru Trilogie'},
    { zitat: 'Das ist also mein Leben. Und ich will, dass du weißt, ich bin glücklich und traurig zugleich und versuche noch immer herauszufinden, wie das eigentlich sein kann. ', autor: 'Stephen Chbowsky ', werk: 'Das ist also mein Leben'},
    { zitat: 'Denn Zeit ist Leben. Und das Leben wohnt im Herzen. ', autor: 'Michael Ende ', werk: 'Momo'}
  ]